---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[mumble::default]
  - name: server
    provisioner:
      named_run_list: server
